//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanHackAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Fulltext { get; set; }
        public string UserId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Edited { get; set; }
        public int TopicId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
